---

#
### main playbook for configuration of workstations.
#

- include_tasks: redhat.yml
  when: ansible_facts['os_family'] == "RedHat"

- include_tasks: debian.yml
  when: ansible_facts['os_family'] == "Debian" or ansible_facts['os_family'] == "Pop!_OS"

- include_tasks: archlinux.yml
  when: ansible_facts['os_family'] == "Archlinux"
